const endpoints = {
  truckCoversPricesUrl: '/truckcovers-prices',
  truckCoversEditPricesUrl: '/truckcovers-prices/edit',
  truckGondolaPricesUrl: '/truck-gondola-prices',
  truckGondolaEditPricesUrl: '/truck-gondola-prices/edit',
  truckWithShutterPriceUrl: '/truck-with-shutter-price',
  truckWithShutterEditPriceUrl: '/truck-with-shutter-price/edit',
  truckWithoutShutterPriceUrl: '/truck-without-shutter-price',
  truckWithoutShutterEditPriceUrl: '/truck-without-shutter-price/edit',
  truckGondolaPriceUrl: '/truckcovers-gondola-priceoffer',
  truckShutterPriceUrl: '/truckcovers-shutter-priceoffer',
  truckFileUrl: '/truckcovers-offer-file',
  truckComparedFilesUrl: '/truckcovers-offer-file-edit',
  truckSendEmailUrl: '/truckcovers-offer-email',
  windproofPricesUrl: '/windproofcurtains-prices',
  windProofEditPricesUrl: '/windproofcurtains-prices/edit',
  windproofPriceUrl: '/windproofcurtains-priceoffer',
  windproofFileUrl: '/windproofcurtains-offer-file',
  windproofComparedFilesUrl: '/windproofcurtains-offer-file-edit',
  windproofSendEmailUrl: '/windproofcurtains-offer-email',
  verifyTokenUrl: '/verify-token',
  contactUrl: '/contact',
  register: '/register',
  login: '/login',
  logout: '/logout',
  user: '/:userId',
  userId:'/:id',
  users: '/'
};

module.exports = endpoints;